#! /bin/bash

# the portion of building a livecd that needs to be run as root
# run this after running build-livecd
#
# The temp dir in which things happen is by default deleted when this
# script ends, unless an error happens or the KEEP_TMPDIR variable is set

function cleanup() {
    if [ -n "$KEEP_TMPDIR" ]; then
        echo "Not removing tmpdir $tmpdir"
    else
        [ -d $tmpdir ] && rm -rf $tmpdir
    fi
}

if [ $(id -u) != 0 ]; then
  echo "Please run this script as root"
  exit 1
fi

trap cleanup EXIT

resultdir=$PWD
srcdir=$(realpath $(dirname $0))
tmpdir=$(mktemp -d /var/tmp/build-livecd-XXXXXX)

cd $srcdir
last_tag=$(git describe)

cd $tmpdir
echo Working in directory $tmpdir

#echo "* Running livecd-creator"
#livecd-creator -v --cache /var/cache/microkernel --config $srcdir/microkernel.ks -f microkernel || KEEP_TMPDIR=yes

echo "* Converting to initrd"
#livecd-iso-to-pxeboot $
microkernel.iso || KEEP_TMPDIR=yes
#mkinitfs -o $tmpdir/microkernel.iso || KEEP_TMPDIR=yes
mkinitfs -o /tmp/microkernel.cpio.gz

echo "* Building tarball"
mkdir microkernel
mv /tmp//initrd0.img /media/cdrom/boot/vmlinuz microkernel || KEEP_TMPDIR=yes
cd microkernel
cat > README <<EOF
This is a Microkernel for the new Razor
(https://github.com/puppetlabs/razor-server)

The microkernel was built from https://github.com/puppetlabs/razor-alpine-ppc64le-mk
at commit $last_tag

For instructions on how to set things up, read
https://github.com/puppetlabs/razor-server/wiki/Installation

To verify the kernel and initrd in this tar, run

  sha256sum -c SHA256SUM

The SHA256SUM file is signed with my public key (FC6E8A22). You can verify it
by running

  gpg --verify SHA256SUM.sig
EOF

sha256sum initrd0.img vmlinuz0 > SHA256SUM

cd ..
tarball=$srcdir/pkg/microkernel-${last_tag#release-}.tar
tar cf $tarball microkernel/
chown --reference $srcdir/build-livecd $tarball

echo "* Done"
echo "The microkernel is in $tarball"
